# Generated by Django 5.2.4 on 2025-07-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grupos aos quais o usuário pertence.",
                related_name="perfil_groups",
                to="auth.group",
                verbose_name="Grupos",
            ),
        ),
    ]
