# Generated by Django 5.2.4 on 2025-07-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0002_perfil_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="codigo_vendedor",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Código do Vendedor"
            ),
        ),
    ]
