# Generated by Django 5.2.4 on 2025-07-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0003_perfil_codigo_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="codigo_vendedor",
            field=models.CharField(max_length=10, verbose_name="Código do Vendedor"),
        ),
    ]
