# Generated by Django 5.2.4 on 2025-07-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0004_alter_perfil_codigo_vendedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="groups",
        ),
    ]
