# Generated by Django 5.2.4 on 2025-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0006_alter_perfil_codigo_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="codigo_vendedor",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código do Vendedor"
            ),
        ),
    ]
