# Generated by Django 5.2.4 on 2025-07-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0007_alter_perfil_codigo_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
