# Generated by Django 5.2.4 on 2025-07-22 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitacao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaoorcamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberta", "Aberta"),
                    ("declinada", "Declinada"),
                    ("finalizada", "Finalizada"),
                ],
                default="aberta",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacaoorcamento",
            name="vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitacoes_orcamento",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendedor",
            ),
        ),
    ]
